### ISSUE TITLE
Cannot start ArbGW if TeraAPI not started

### ISSUE THREAD

**Issue by tsukasaroot** [Archgeus/TERA-Server-Manager#1]
Hello o/ Very cool tool there!

In my use case, I have a custom Tera API, which is hosted on another server, so not locally at same place of server Binaries.
Like there's a hardcoded check, it's not possible to bypass this and start server without it.

If we want to take an easy path, I think that if a path is not set for TeraAPI, the check shouldn't occure on line 1004 of TERA_Panel.cs
On my side, altering line for this worked for my use case: 
`if (!string.IsNullOrEmpty(TeraApiPath) && (TeraApiPID == -1 || !Process.GetProcesses().Any((Process p) => p.Id == TeraApiPID)))`

And should show error message only if the path for TeraApi is set, I let it up to you to update it incase someone else need it o/

**Comment by Archgeus** [comment]
[Done.](https://github.com/Archgeus/TERA-Server-Manager/releases/tag/1.7.6)

Thanks for the suggestion.
